version: '3'

services:
  influxdb:
    image: influxdb:alpine
    ports:
      - 8086:8086
    volumes:
      - ./influxdata:/var/lib/influxdb:rw
    environment:
      INFLUXDB_DB: "stocks"
      INFLUXDB_USER: "stocklogger"
      INFLUXDB_USER_PASSWORD: "${INFLUXDB_USER_PASSWORD}"
      INFLUXDB_READ_USER: "stockreader"
      INFLUXDB_READ_USER_PASSWORD: "${INFLUXDB_READ_USER_PASSWORD}"

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - ./grafanadata:/var/lib/grafana:rw
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
  
  stock-logger:
    build: stockLogger
    depends_on:
      - influxdb
    environment:
      ALPHAVANTAGE_APIKEY: "${ALPHAVANTAGE_APIKEY}"
      INFLUX_URL: "influxdb"
      INFLUX_USER: "stocklogger"
      INFLUX_PASSWORD: "${INFLUXDB_USER_PASSWORD}"
      INFLUX_DB: "stocks"
